# When a tagged commit is pushed the documentation pages and npm module are published/deployed:
os: linux
# linux dist that includes C++ compiler needed for native node modules
dist: bionic
# npm version patch -m "%s Release"
language: node_js
node_js:
  - "lts/*"
env:
  - REPO_VER=v1.4.1 MSSQL_VER=2019 MSSQL_SA_PWD=sqlS3rv35local MSSQL_PWD=390Khy7MxeU8N
before_install:
  - wget -O install-mssql.sh https://raw.githubusercontent.com/ugate/repo/$REPO_VER/mssql/install.sh
  - bash ./install-mssql.sh
  - rm -rf install-mssql.sh
  - odbcinst -j
  - odbcinst -q -d
  - odbcinst -q -s
branches:
  only:
    - master
    - "/v*/"
script:
# - printenv
  - "npm test"
deploy:
  #edge: true # avoid dpl v2 missing api_token
  - provider: script
    skip_cleanup: true # deprecated, use cleanup with new dpl ver
    cleanup: false
    script: npm run jsdocp-deploy
    on:
      tags: true # only on tagging commit
      branch:
        - /v(\d+\.)?(\d+\.)?(\*|\d+)$/
  - provider: npm
    skip_cleanup: false # deprecated, use cleanup with new dpl ver
    cleanup: true
    email: "ugate.public@gmail.com"
    api_token: $NPM_TOKEN  # Set in the settings page of your repository, as a secure variable
    on:
      tags: true # only on tagging commit
      branch:
        - /v(\d+\.)?(\d+\.)?(\*|\d+)$/