version: '3.9'
x-env: &env-vars
  SA_PASSWORD: sqlS3rv35local
  MSSQL_DATABASE: sqlermssql
  MSSQL_PORT: 1433
  ACCEPT_EULA: Y
  #MSSQL_PID: Express
x-env-sqler: &env-tokens
  GITHUB_TOKEN: ${GITHUB_TOKEN}
  NPM_TOKEN: ${NPM_TOKEN}
services:
  # MySQL: https://hub.docker.com/_/mysql
  sqler_mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqler_mssql
    restart: unless-stopped
    environment:
      <<: *env-vars
    networks:
      - app
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
      timeout: 20s
      retries: 10
    ports:
      - 1433:1433
  # NodeJS for sqler dialect testing
  sqler_mssql_dialect:
    container_name: sqler_mssql_dialect
    depends_on:
      - sqler_mssql
    build:
      context: .
      dockerfile: Dockerfile.ci
      args:
        <<: *env-vars
    links:
      - "sqler_mssql:sqler_mssql_database"
    networks:
      - app
    healthcheck:
      test: curl --fail http://localhost:80/healthcheck || exit 1
      timeout: 20s
      retries: 10
    ports:
      - 4002:80
    restart: unless-stopped
    environment:
      <<: [ *env-vars, *env-tokens ]
    volumes:
      - ./docs:/home/node/app/docs
networks:
  app:
    driver: bridge
    name: sqler_mssql_net